#!/usr/bin/env bash
set -e -o pipefail

# Add repo specific metadata here.

PACKAGE_NAME="Gitolite"
UPSTREAM_IMAGE_CONFIG_KEY_PREFIX="BASE_IMAGE"
UPSTREAM_VERSION_CONFIG_KEY="GITOLITE_VERSION"
UPSTREAM_GIT_REPO="https://github.com/sitaramc/gitolite"
TEST_TYPE="background"
TEST_CONTAINER_TYPE="gitolite"
TEST_CONTAINER_START_WAIT_SECONDS="10"

current_upstream_version() {
    get_config_arg ${UPSTREAM_VERSION_CONFIG_KEY:?}
}

latest_upstream_version() {
    git_repo_latest_tag "${UPSTREAM_GIT_REPO:?}.git"
}

update_latest_upstream_version() {
    local cur_ver="${1:?}"
    local latest_ver="${2:?}"
    echo "Updating ${PACKAGE_NAME:?} ${UPSTREAM_VERSION_CONFIG_KEY:?} '${cur_ver:?}' -> '${latest_ver:?}'"
    set_config_arg "${UPSTREAM_VERSION_CONFIG_KEY:?}" "${latest_ver:?}"
    git add ${ARGS_FILE:?}
}

test_start_container() {
    local container_name="${1:?}"
    docker run \
        --name ${container_name:?} \
        --detach \
        --rm \
        --publish 127.0.0.1:2222:2222 \
        ${IMAGE:?}
}

test_image_after_container_startup() {
    # TODO: Add tests.
    :
}
